baseurl = "https://davidthinks.com/sr"
title = "David Thinks..."
contentdir = "content/sr"
publishdir = "public/sr"
staticdir = "static/sr"
uglyURLs = "true"
noTimes = "true"

[params]
  hostname = "davidthinks.com"
  locale = "sr"
  environment = "live"