baseurl = "https://davidthinks.com"
title = "David Thinks..."
contentdir = "content/sr"
publishdir = "public/sr"
staticdir = "static"
uglyURLs = "false"

[params]
  locale = "sr"
  environment = "local"