baseurl = "https://davidthinks.com/en"
title = "David Thinks..."
contentdir = "content/en"
publishdir = "public/en"
staticdir = "static"
uglyURLs = "false"

[params]
  locale = "en"
  environment = "live"

