baseurl = "https://davidthinks.com"
title = "David Thinks..."
contentdir = "content/sr"
publishdir = "public/sr"
staticdir = "static"
uglyURLs = "true"
noTimes = "true"

[params]
  hostname = "localhost"
  locale = "sr"
  environment = "local"