baseurl = "https://davidthinks.com/sr"
title = "David Thinks..."
contentdir = "content/sr"
publishdir = "public/sr"
staticdir = "static"
uglyURLs = "true"

[params]
  locale = "sr"
  environment = "live"